#!/usr/bin/env bash

brew install coreutils
brew install git
brew install jq
brew install htop
brew install kubernetes-cli
brew install maven
brew install gradle
brew install midnight-commander
brew install node
brew install pass
brew install pgcli
brew install redis
brew install terminal-notifier
brew install tmux
brew install transmission
brew install tree
brew install youtube-dl
brew install zsh
brew install zsh-completions
brew install wget
brew install gnu-tar
brew install automake
brew install libtool
brew install hub
brew install ffmpeg
brew install wget
brew install mkvirtualenv
brew install watch
brew install automake
brew install libtool
brew install gnu-tar
brew install telnet
brew install certbot
brew install ssh-agent
brew install sslscan
brew install nmap
brew install csshx
brew install knock
brew install lftp
brew install ossp-uuid
brew install wireshark